import { Shelter } from './types';
import { NewShelterInput } from '../../backend/src/dtos/newShelterDTO';
import { DayOfWeek } from '../../backend/src/types';

export const ExampleShelters: NewShelterInput[] = [
  {
    name: 'BAGLY',
    address: {
      street: '123 Main St',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
    },
    latitude: 42.3611,
    longitude: -71.0579,
    description: 'Description.',
    rating: 4.5,
    availability: 'Open',
    phone_number: '555-0123',
    email_address: 'contact@shelter.org',
    website: 'https://www.bagly.org/',
    hours: {
      [DayOfWeek.MONDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
      [DayOfWeek.TUESDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: true,
      },
      [DayOfWeek.WEDNESDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
      [DayOfWeek.THURSDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
      [DayOfWeek.FRIDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
      [DayOfWeek.SATURDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
      [DayOfWeek.SUNDAY]: {
        opening_time: '09:00:00',
        closing_time: '21:00:00',
        is_closed: false,
      },
    },
    picture: [
      'https://shelter-link-shelters.s3.us-east-2.amazonaws.com/test_photo.webp',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
    ],
  },
  // {
  //   id: 2,
  //   name: 'Shelter Two',
  //   description: 'Longer description 2',
  //   latitude: 42.3584,
  //   longitude: -71.065,
  //   emoji: '🏳️‍⚧️',
  //   address: {
  //     street: '123 Main St',
  //     city: 'Boston',
  //     state: 'MA',
  //     zipCode: '02108',
  //   },
  //   overall_rating: 4.5,
  //   inclusivity_rating: 4.9,
  //   safety_rating: 4.7,
  //   availability: 'Open',
  //   phone_number: '555-0123',
  //   email_address: 'contact@shelter.org',
  //   opening_time: '09:00:00',
  //   closing_time: '21:00:00',
  //   picture: [
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //   ],
  // },
  // {
  //   id: 3,
  //   name: 'Shelter Three',
  //   description: 'Longer description 3',
  //   latitude: 42.2995,
  //   longitude: -71.0649,
  //   emoji: '🔅',
  //   address: {
  //     street: '123 Main St',
  //     city: 'Boston',
  //     state: 'MA',
  //     zipCode: '02108',
  //   },
  //   overall_rating: 4.3,
  //   inclusivity_rating: 4.9,
  //   safety_rating: 4.7,
  //   availability: 'Open',
  //   phone_number: '555-0123',
  //   email_address: 'contact@shelter.org',
  //   opening_time: '09:00:00',
  //   closing_time: '21:00:00',
  //   picture: [
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //   ],
  // },
  // {
  //   id: 4,
  //   name: 'Shelter Four',
  //   description: 'Longer description 4',
  //   latitude: 42.3657,
  //   longitude: -71.0824,
  //   emoji: '🩵',
  //   address: {
  //     street: '123 Main St',
  //     city: 'Boston',
  //     state: 'MA',
  //     zipCode: '02108',
  //   },
  //   overall_rating: 4.2,
  //   inclusivity_rating: 4.9,
  //   safety_rating: 4.7,
  //   availability: 'Open',
  //   phone_number: '555-0123',
  //   email_address: 'contact@shelter.org',
  //   opening_time: '09:00:00',
  //   closing_time: '21:00:00',
  //   picture: [
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //     'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
  //   ],
  // },
];
export { Shelter };
