import { Shelter } from './types';

export const ExampleShelters: Shelter[] = [
  {
    id: 1,
    name: 'BAGLY',
    description: 'Description.',
    latitude: 42.3611,
    longitude: -71.0579,
    emoji: '🏳️‍🌈',
    address: {
      street: '123 Main St',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
    },
    overall_rating: 3.9,
    inclusivity_rating: 4.9,
    safety_rating: 4.7,
    availability: 'Open',
    phone_number: '555-0123',
    email_address: 'contact@shelter.org',
    opening_time: '09:00:00',
    closing_time: '21:00:00',
    picture: [
      'https://shelter-link-shelters.s3.us-east-2.amazonaws.com/test_photo.webp',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978'
    ],
  },
  {
    id: 2,
    name: 'Shelter Two',
    description: 'Longer description 2',
    latitude: 42.3584,
    longitude: -71.065,
    emoji: '🏳️‍⚧️',
    address: {
      street: '123 Main St',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
    },
    overall_rating: 4.5,
    inclusivity_rating: 4.9,
    safety_rating: 4.7,
    availability: 'Open',
    phone_number: '555-0123',
    email_address: 'contact@shelter.org',
    opening_time: '09:00:00',
    closing_time: '21:00:00',
    picture: [
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
    ],
  },
  {
    id: 3,
    name: 'Shelter Three',
    description: 'Longer description 3',
    latitude: 42.2995,
    longitude: -71.0649,
    emoji: '🔅',
    address: {
      street: '123 Main St',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
    },
    overall_rating: 4.3,
    inclusivity_rating: 4.9,
    safety_rating: 4.7,
    availability: 'Open',
    phone_number: '555-0123',
    email_address: 'contact@shelter.org',
    opening_time: '09:00:00',
    closing_time: '21:00:00',
    picture: [
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
    ],
  },
  {
    id: 4,
    name: 'Shelter Four',
    description: 'Longer description 4',
    latitude: 42.3657,
    longitude: -71.0824,
    emoji: '🩵',
    address: {
      street: '123 Main St',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
    },
    overall_rating: 4.2,
    inclusivity_rating: 4.9,
    safety_rating: 4.7,
    availability: 'Open',
    phone_number: '555-0123',
    email_address: 'contact@shelter.org',
    opening_time: '09:00:00',
    closing_time: '21:00:00',
    picture: [
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
      'https://www.bostonherald.com/wp-content/uploads/2020/07/best018.jpg?w=978',
    ],
  },
];
export { Shelter };
